/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class AddTaskfeedTasksFromTemplateAction {
    global AddTaskfeedTasksFromTemplateAction() {

    }
    @InvocableMethod(label='Add Taskfeed Tasks From Template')
    global static List<Id> addTaskfeedTasksFromTemplate(List<taskfeed1.AddTaskfeedTasksFromTemplateAction.AddTaskfeedTasksFromTemplateActionRequest> requests) {
        return null;
    }
global class AddTaskfeedTasksFromTemplateActionRequest {
    @InvocableVariable( required=false)
    global Id boardId;
    @InvocableVariable( required=false)
    global Id listId;
    @InvocableVariable( required=false)
    global Id templateId;
    @InvocableVariable( required=false)
    global String templateName;
    global AddTaskfeedTasksFromTemplateActionRequest() {

    }
}
}
