/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class iCalendarEvent {
    global String categories;
    global String description;
    global Datetime dtend;
    global Datetime dtstamp;
    global Datetime dtstart;
    global Date endDate;
    global String location;
    global Integer sequence;
    global Date startDate;
    global String summary;
    global String uid;
    global String url;
    global iCalendarEvent() {

    }
    global String getVEvent() {
        return null;
    }
}
