/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class TaskHelper {
    global TaskHelper() {

    }
global class AgileTask {
    global AgileTask() {

    }
}
global class Board {
    global Board() {

    }
}
global class BoardSummary {
    global BoardSummary() {

    }
}
global class Boards {
    global Boards() {

    }
}
global class Category {
    global Category() {

    }
}
global class CustomLabel {
    global CustomLabel(String n, String o, String r, String f, String v, Boolean show, String bg, String font, String ic) {

    }
}
global class Filters {
    global Filters() {

    }
    global void cleanFilters() {

    }
}
global class Person {
    global Person() {

    }
}
global class TaskList {
    global TaskList() {

    }
}
global class TaskSummary {
    global TaskSummary() {

    }
}
global class TimeLog {
    global TimeLog() {

    }
}
}
