/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class TaskControllerExtension {
    @RemoteAction
    global static String UploadAttachment(String filename, String fileContent, String id) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.Person> addContributor(String userId, String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> assignChecklistItem(String ownerId, String itemId, String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> changeChecklistItemValue(Boolean checkValue, String itemId, String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> createChecklistItem(String name, String taskId) {
        return null;
    }
    @RemoteAction
    global static List<SObject> findSObjects(String obj, String qry, String addFields) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> getChecklistItems(String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.Person> getContributors(String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.Person> getFollowers(String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.Person> removeContributor(String userId, String taskId) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> reorderChecklistItems(String itemIdCSV) {
        return null;
    }
    @RemoteAction
    global static List<taskfeed1.TaskHelper2.ChecklistItem> updateChecklistItem(String name, String itemId, String taskId) {
        return null;
    }
}
