/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class TaskHelper2 {
    global TaskHelper2() {

    }
global class AgileTask implements System.Comparable {
}
global class Board implements System.Comparable {
}
global class BoardSummary {
    global BoardSummary() {

    }
}
global class Boards {
}
global class Category {
    global Category() {

    }
}
global class ChecklistItem {
}
global class CustomLabel {
}
global class Filters {
}
global class InboxTaskList {
}
global class Notification {
}
global class NotificationResults {
    global NotificationResults() {

    }
}
global class Person {
    global Person() {

    }
}
global class RequestWrapper {
    global RequestWrapper() {

    }
}
global class ResponseWrapper {
    global ResponseWrapper() {

    }
}
global class TaskList {
}
global class TaskSummary {
    global TaskSummary() {

    }
}
global class TimeLog {
}
}
